#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with and sleep for 2 and then print invincible.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
