#!/usr/bin/env bash
# Print Best school 10 times.
#   and there is a conditon on the 9th.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
